const products = [
  {
    _id: '1',
    name: 'Classic Plague Doctor',
    image: '/images/classic-plague.jpg',
    description:
      'A classic plague doctor ready to step in as a first responder',
    brand: 'male',
    category: 'Mens',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Darth Vader',
    image: '/images/darthVader.jpg',
    description: 'With this costume the galaxy awaits in fear.',
    brand: 'Female',
    category: 'Womens',
    price: 99.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Egyption Goddess',
    image: '/images/egyptian-goddess-costume.jpg',
    description: 'Rule the nile as this egyption goddess',
    brand: 'female',
    category: 'Womens',
    price: 68.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Flapper girl',
    image: '/images/flapperGirl.jpg',
    description:
      "Enjoy the roaring 20's with an outfit that is never out of style",
    brand: 'female',
    category: 'Womens',
    price: 39.99,
    countInStock: 11,
    rating: 5,
    numReviews: 7,
  },
  {
    _id: '5',
    name: 'Ghost Buster Lady',
    image: '/images/ghostBustersW.jpg',
    description: 'Make sure you dont cross steams ',
    brand: 'female',
    category: 'Womens',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Goku',
    image: '/images/goku.jpg',
    description: 'Help save the earth with the rest of the z-fighters',
    brand: 'male',
    category: 'Mens',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 4,
  },
  {
    _id: '7',
    name: 'Master Roshi',
    image: '/images/master-roshi.jpg',
    description: 'Bring out your energy ray',
    brand: 'male',
    category: 'Mens',
    price: 39.99,
    countInStock: 2,
    rating: 4,
    numReviews: 15,
  },
  {
    _id: '8',
    name: 'Prince',
    image: '/images/purple-rock-legend.jpg',
    description: 'Take out your red corvette',
    brand: 'male',
    category: 'Mens',
    price: 49.99,
    countInStock: 2,
    rating: 4,
    numReviews: 16,
  },
  {
    _id: '9',
    name: 'Classic Rapper',
    image: '/images/rapper.jpg',
    description: 'It is hammer time tonight',
    brand: 'male',
    category: 'Mens',
    price: 39.99,
    countInStock: 4,
    rating: 4,
    numReviews: 3,
  },
  {
    _id: '10',
    name: 'Samurai Warrior',
    image: '/images/samurai-warrior.jpg',
    description: 'Help the shogun with this costume',
    brand: 'male',
    category: 'Mens',
    price: 69.99,
    countInStock: 0,
    rating: 4,
    numReviews: 2,
  },
  {
    _id: '11',
    name: 'The last Centurian ',
    image: '/images/spartan-warrior.jpg',
    description: 'This noble fighter defends all.',
    brand: 'male',
    category: 'Mens',
    price: 49.99,
    countInStock: 5,
    rating: 4,
    numReviews: 5,
  },
  {
    _id: '12',
    name: 'spiderWoman',
    image: '/images/spiderWoman.jpg',
    description: 'This slick web slinger has all the moves',
    brand: 'male',
    category: 'Womens',
    price: 99.99,
    countInStock: 4,
    rating: 4,
    numReviews: 5,
  },
  {
    _id: '13',
    name: 'Velma',
    image: '/images/velma.jpg',
    description: 'OH jinkies I have a clue ',
    brand: 'male',
    category: 'Womens',
    price: 29.99,
    countInStock: 3,
    rating: 4,
    numReviews: 7,
  },
  {
    _id: '14',
    name: 'Plague Doctor Lady',
    image: '/images/womens-plague.jpg',
    description: 'Help save your community',
    brand: 'male',
    category: 'Womens',
    price: 79.99,
    countInStock: 2,
    rating: 4,
    numReviews:8,
  },
  {
    _id: '15',
    name: 'Dr. Evil',
    image: '/images/drEvil.jpg',
    description: 'We ask for 100 Billion Dollars',
    brand: 'male',
    category: 'Mens',
    price: 79.99,
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Top Gun Pilot',
    image: '/images/topGun.jpg',
    description: 'Find your Maverick',
    brand: 'male',
    category: 'Womens',
    price: 59.99,
    countInStock: 2,
    rating: 4,
    numReviews: 11,
  },
];

export default products;
